config/routes.rb
require 'subdomain'
Squadlink::Application.routes.draw do
  resources :blogs
  get "/termsofservice" => "public#termsofservice",  :as => :termsofservice
  get "/privacy_policy" => "public#privacy_policy",  :as => :privacy_policy
  get "/pricing" => "public#pricing",  :as => :pricing
  get "/index" => "public#index",  :as => :index

  resources :guides
  post "hooks/receiver"
    resources :firms
    post "public/create_firm" => "public#create_firm", :as => :create_firm
    resources :public do
      member do
        get "first_user"
        post "create_first_user"
     end
  end  
  ActiveAdmin.routes(self)
  get '/obeqaslksdssdfnfdfysdfxm/dashboard/subscription_chart_data' =>  'obeqaslksdssdfnfdfysdfxm/dashboard#subscription_chart_data'
  get '/obeqaslksdssdfnfdfysdfxm/dashboard/firms_chart_data' =>  'obeqaslksdssdfnfdfysdfxm/dashboard#firms_chart_data'
  get '/obeqaslksdssdfnfdfysdfxm/dashboard/firms_resources_chart_data' =>  'obeqaslksdssdfnfdfysdfxm/dashboard#firms_resources_chart_data'
  get '/obeqaslksdssdfnfdfysdfxm/dashboard/new_firms_count_chart_data' =>  'obeqaslksdssdfnfdfysdfxm/dashboard#new_firms_count_chart_data'
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for  :users,
              :path_names => { :sign_up => "register" },
              :controllers => {
              :sessions => "sessions",
              :passwords => "passwords",
              :registrations => "users"
             }

  devise_scope :user do
  	get "/sign_in", :to => "sessions#new"
    delete "/sign_out", :to => "sessions#destroy"
    get "register", :to => "public#register"
  	get "contact", :to => "public#contact"
    get "/sign_in_at_subdomain" =>  "sessions#sign_in_at_subdomain", :as => :sign_in_at_subdomain
  	get "/register/:firm_id/user" => "public#first_user",  :as => :register_user
  	post "/register/:firm_id/user" => "public#create_first_user",  :as => :create_first_user
  	get "/validates_uniqe/:subdomain" => "public#validates_uniqe", :as => :validates_uniqe
    get '/users/password/edit' =>  'devise/passwords#edit', :as => :edit_password
  end
  
  


  constraints(Subdomain) do
    post 'emails/create/:id' => 'emails#create', as: :emails
    get 'emails/:id/new' => 'emails#new', as: :new_email
    get 'emails/:id/reminder' => 'emails#reminder', as: :reminder_email
    post 'emails/reminder_create/:id' => 'emails#reminder_create', as: :reminder_create
    get "/emails/quick_send/:id" => "emails#quick_send", :as => :quick_send
    get "plans" => 'plans#index', :as => :plans
    # delete "plans/index", :as => :plans_delete
    get "plans/cancel", :as => :plans_cancel
    resources :subscriptions
    get "payments" => 'payments#index', :as => :payments
    get "payments/:id" => 'payments#show', :as => :payment
    get "payments/download_pdf/:id" => 'payments#download_pdf', :as => :download_pdf
    constraints(PaymentChecker) do
      # devise_for  :users
      resources :users, :only => [:index, :show, :edit, :create, :update, :destroy] do
        member do
         get :valid
        end
      end
      #chart_controller
      get "charts" => "charts#index", :as => :charts
      get "users_logs" => "charts#users_logs",  :as => :users_logs
      get "project_users_logs" => "charts#project_users_logs",  :as => :project_users_logs
      get "project_todos_logs" => "charts#project_todos_logs",  :as => :project_todos_logs
      # get "customer_users_logs" => "charts#customer_users_logs",  :as => :customer_users_logs
      # get "customer_todos_logs" => "charts#customer_todos_logs",  :as => :customer_todos_logs
      get "projects_logs" => "charts#projects_logs",  :as => :projects_logs
      get "customers_logs" => "charts#customers_logs",  :as => :customers_logs
      get "dashboard_json" => "charts#dashboard_json",  :as => :dashboard_json
      get "statistics" => "charts#statistics",  :as => :statistics
      get "economicstatistics_json" => "charts#economicstatistics_json",  :as => :economicstatistics_json
      #projects_controller
      get "/archive" => "projects#archive",  :as => :archive
      put "projects/update_index/:id" => "projects#update_index",  :as => :update_index
      post "projects/create_index/" => "projects#create_index",  :as => :create_index
      post "/activate_projects/:id" => "projects#activate_projects", :as => :activate_projects
      #tabs_controller
      get "/:class/:id/state"       => "tabs#state", :as => :tabs_state
      get "/:class/:id/tasks"       => "tabs#todos", :as => :tabs_todos
      get "/:class/:id/milestones"  => "tabs#milestones", :as => :tabs_milestones
      get "/:class/:id/projects"    => "tabs#projects", :as => :tabs_projects
      get "/:class/:id/employees/"  => "tabs#employees", :as => :tabs_employees
      get "/:class/:id/logs"        => "tabs#logs", :as => :tabs_logs
      get "/:class/:id/users"       => "tabs#users", :as => :tabs_users
      get "/:class/:id/statistics"  => "tabs#statistics", :as => :tabs_statistics
      get "/:class/:id/spendings"   => "tabs#spendings", :as => :tabs_spendings
      get "/:class/:id/invoices"    => "tabs#invoices", :as => :tabs_invoices
      #logs_controller
      post "logs/start_tracking" => "logs#start_tracking",  :as => :start_tracking
      patch "logs/stop_tracking/:id" => "logs#stop_tracking",  :as => :stop_tracking
      get "/get_logs_todo/:todo_id" => "logs#get_logs_todo", :as => :get_logs_todo
      #select_controller
      get "/project_select/:project_id/:log_id" => "select#project_select"
      get "/project_select/:project_id/" => "select#project_select"

      get "/customer_select/:customer_id/:log_id" => "select#customer_select"
      get "/customer_select/:customer_id/" => "select#customer_select"
      get "/todo_select/:todo_id/:log_id" => "select#todo_select"
      get "/todo_select/:todo_id/" => "select#todo_select"
      post "/customer_select_tracking/:customer_id/:log_id" => "select#customer_select_tracking"
      post "/customer_select_tracking/:customer_id/" => "select#customer_select_tracking"

      post "/employee_select_tracking/:employee_id/:log_id" => "select#employee_select_tracking"
      post "/employee_select_tracking/:employee_id/" => "select#employee_select_tracking" 

      post "/project_select_tracking/:project_id/:log_id" => "select#project_select_tracking"
      post "/project_select_tracking/:project_id/" => "select#project_select_tracking"
      
      post "/todo_select_tracking/:todo_id/:log_id" => "select#todo_select_tracking"
      post "/todo_select_tracking/:todo_id/" => "select#todo_select_tracking"

      #timesheets_controller
      get "/timesheetWeek"   => "timesheets#timesheet_week"
      get "/timesheetMonth"  => "timesheets#timesheet_month"

      get "/:class/:id/timesheet_day/:date"   => 'timesheets#timesheet_day',   :as => :timesheet_day
      get "/:class/:id/timesheet_week/:date"   => 'timesheets#timesheet_week',   :as => :timesheet_week
      get "/:class/:id/timesheet_month/:date"  => "timesheets#timesheet_month",  :as => :timesheet_month
      
      post "/add_hour_to_project/" => 'timesheets#add_hour_to_project', :as => :add_hour_to_projects
      post "/add_log_timesheet" => 'timesheets#add_log_timesheet', :as => :add_log_timesheet
      #reports_controller
      get "/reports" => 'reports#index', :as => :reports
      get "/squadlink_report" => 'reports#squadlink_report', :as => :squadlink_report
      get "/dashboard" => 'reports#dashboard', as: :dashboard
      #memberships_controller
      post "/membership/:id/:project_id" => "memberships#index", :as => :membership
      #firms_controller
      put "/firm_update" => "firms#firm_update",  :as => :firm_update
      get "/account" => "firms#firm_show",  :as => :firm_show
      #roster
      get "/roster_milestone" => "roster#get_milestones", :as => :roster_milestone
      get "/roster_task" => "roster#get_tasks", :as => :roster_task
      #timerange
      # get "/logs_pr_date/:time/:url" => "timerange#logs_pr_date", :as => :logs_pr_date
      # match "/logs_pr_date" => "timerange#logs_pr_date", :as => :logs_pr_date
      get "/log_range/" => "timerange#log_range", :as => :log_range
      get "/todo_range/" => "timerange#todo_range", :as => :todo_range
      get "/invoice_range/" => "timerange#invoice_range", :as => :invoice_range
      # get "/todos_pr_date/:time/:url/:id" => "timerange#todos_pr_date", :as => :todos_pr_date 
      #invoices
      get "/invoices/customer_select/" => "invoices#customer_select"
      get "/invoices/project_select/" => "invoices#project_select"
      post "/invoices/customers_create/" => "invoices#customers_create"
      post "/invoices/projects_create/" => "invoices#projects_create"
      get "/invoices/:id/slow_sending/" => "invoices#slow_sending"
      get "/invoices/:id/credit_note/" => "invoices#credit_note"
      post "/invoices/:id/credit_note_create/" => "invoices#credit_note_create", :as => :credit_note_create

      # post "/jobs/sending_invoice/" => "jobs#sending_invoice", :as => :sending_invoice
      post "/jobs/handeling_invoice/" => "jobs#handeling_invoice", :as => :handeling_invoice
      
      get "/jobs/download/:id" => "jobs#download", :as => :download
      post "/jobs/invoice_paid/:id" => "jobs#invoice_paid", :as => :invoice_paid
      post "/jobs/invoice_lost/:id" => "jobs#invoice_lost", :as => :invoice_lost
      patch "/jobs/create_slow_sending/:id" => "jobs#create_slow_sending", :as => :create_slow_sending
      get "/jobs/fetch_job/" => "jobs#fetch_job", :as => :fetch_job
      get "/jobs/ajax_download/" => "jobs#ajax_download", :as => :ajax_download
      get "/jobs/ajax_sending/" => "jobs#ajax_sending", :as => :ajax_sending
      get "/jobs/time_out/" => "jobs#time_out", :as => :time_out
      get "jobs/download_invoice/:id" => "jobs#download_invoice", :as => :download_invoice
      get "jobs/show_pdf/:id" => "jobs#show_pdf", :as => :show_pdf
      get "/invoice_pdf/:id" => "pdf#invoice", :as => :invoice_pdf

app/models/project.rb
class Project < ActiveRecord::Base
  include ActiveModel::Validations
  validates_with Validator
  validates_with MadeWithInLimit, on: :create

  belongs_to :firm, :counter_cache => true
  belongs_to :customer
  has_many :todos, :dependent => :destroy
  has_many :logs
  has_many :recent_logs, -> {  where('log_date >= ?', Time.zone.now.beginning_of_week).order("log_date DESC") }, :class_name => "Log"
  has_many :milestones, :dependent => :destroy
  has_many :invoices
  validates_presence_of :name
  has_many :memberships
  has_many :users, :through => :memberships
  scope :is_active, -> {where(["active = ?", true])}
  scope :is_inactive, -> {where(["active = ?", false])}
  scope :order_by_name, -> {order("name ASC")}
end 

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
      @project = current_firm.projects.new
    if current_user.role == "external_user"
      @projects = current_user.projects.includes(:firm)
    else
      @projects = current_firm.projects.where(:active => true).includes(:firm).order_by_name
    end
  end
  
  def edit
    @project = Project.find(params[:id]) 
    authorize! :manage, @project
    @customers = current_firm.customers
    respond_to do |format|
        format.js
    end
  end
  

  def show
    @klass = current_firm.projects.find(params[:id]) 
    authorize! :manage, @klass
    redirect_to(tabs_state_path(string_for_klass(@klass),@klass.id))
  end

  def create
    
    @klass = current_firm.projects.new(permitted_params.project)
    @project = current_firm.projects.new
    @klass.active = true
    @klass.users << current_user
    authorize! :manage, @klass
    respond_to do |format|
      if @klass.save
        flash[:notice] = flash_helper((t'activerecord.models.project.one').capitalize + ' ' + (t'activerecord.flash.saved'))
        format.js
      else
        format.js { render "shared/validate_create" }
      end
    end
    
  end
  
  def update
    @klass = Project.find(params[:id])
    @klass.firm = current_firm
    respond_to do |format|
      if @klass.update_attributes(permitted_params.project)
        flash[:notice] = flash_helper("#{@klass.name}" + ' ' + (t'activerecord.flash.saved'))
        format.js
      else
        format.js { render "shared/validate_update" }
       
      end
    end
    
  end
  
  def destroy
    authorize! :archive, Firm
   @klass = Project.find(params[:id])
   
   @klass.destroy
    respond_to do |format|
      flash[:notice] = flash_helper((t'activerecord.models.project.one').capitalize + ' ' + (t'activerecord.flash.deleted'))
      format.js
    end
  end
  
  def archive 
    @projects = current_firm.projects.where(:active => false).order("name ASC")  
  end
  
  def activate_projects
    @project = Project.find(params[:id])
    authorize! :archive,  @project
      if @project.active == true
        @project.active = false
        flash[:notice] = flash_helper("#{@project.name}" + ' ' + (t'general.is_not_active'))
      else
        @project.active = true
        flash[:notice] = flash_helper("#{@project.name}" +' ' + (t'general.is_active'))
      end  
    
    respond_to do |format|
      if @project.save
      format.js
      end
      end
  end
 
end

app/views/projects/_archive.html.erb
<div class="index-view">
	<div class="list_header orange_bgr">
		<%= link_to ((t'general.open').capitalize + ' ' + (t'activerecord.models.project.more')), projects_path, :id => "active_projects"%>
	    <div class="search">
	        <input type="text" autofocus="autofocus" placeholder="<%= t'general.search' %>" name="search" AUTOCOMPLETE=OFF value="" title="search" id="id_search_list">
	    </div>
	</div>
	<div id="cus_pro_us_listing_container">
  <ul id="cus_pro_us_listing">
    <% @projects.each do |project| %>
  <li class="tab_list" id="project_<%= project.id.to_s %>"> 
  	<div class="tab_list_text">
 <%= project.name %>
  </div>
  <div class="button_wrapper">
    <a class="reopen_project button" id="reopen_project_<%= project.id.to_s %>" data-object="project" data-id="<%= project.id.to_s %>"><%= t'general.open' %></a>
    <%= link_to( project_path(project),data: { confirm: 'This will destroy the project and all tasks and logs associated to this project. Are you sure? The project with its tasks and logs will be accessable if you reopen the project.' }, id: "delete_#{project.id.to_s}" , :title => "Delete project", :method => :delete, :remote => true, :class => 'delete_project') do%>
      <span class='button'><%= t'delete' %></span>
    <% end %>
    <% end %>
    </div>
    </li>
  </ul>
  </div>
</div>

app/views/projects/_budget.html.erb
<div class="budget">
  <% if @klass.budget %>
  <div class="state_headers"><%= t('economic.budget') %></div>
  <div class="state_unit">
    <div class="budget_green" data-procent="<%= ProjectPrice.set_procentage(@klass)%>" data-budget="<%= @klass.budget %>"></div>
    <div class="budget_red"></div>
  </div> 
  <% end %>
</div>

app/views/projects/_form.html.erb
<%= form_for(@project, :remote => true) do |f| %>
  <ul>
      <li><%= f.label :name %><%= f.text_field :name, :class => "required", :minlength => "2" %></li>
      <li><%= f.label :description %><%= f.text_area :description %></li>
      <% if @klass.class == Customer %>
      	<%= f.hidden_field :customer_id, value: @klass.id %>
      <% else %>
	      <li><%= f.label :customer %><%= f.select(:customer_id, all_customers.map {|customer| [customer.name, customer.id]}, {:include_blank => t('general.none')})%></li>
	    <% end %>
      <li><%= f.label :budget %><div id="money_input_wrapper"><%= f.text_field(:budget)%> <%= currency_symbol %></div></li>
      <li><%= f.submit (t'save'), :class => 'submit', :id => "submit_project_edit" %></li>
  </ul>
<% end %>

app/views/projects/_navigation_header.html.erb
<% content_for :help do %>
<div class="page_help">
	<div class="page_help_container">
		<%= t "help.projects_show_html" %>
	</div>
</div>
<% end %>

<nav id="html_tabs" class="orange_bgr">
  <div class="name_and_back_button">
    <%= truncate(@klass.name, length: 100, omission: "") %>
    <% if can? :manage, @klass %>
      <span class="open_project_update edit_text" id="project_update" data-id="<%= @klass.id %>" data-object="project"><%= t('edit') %></span>
    <% end %>
    <div class="dialog_form" id="project_update_<%=@klass.id %>_form" title="<%= t'helpers.submit.update', model: Project.model_name.human %>" style="display:none;"></div>
  </div>
  <ul>
  	<li class="">
    	<%=link_to (t"navigation.home"), tabs_state_path(string_for_klass(@klass),@klass.id), class: "tab_state"%>
    </li>
    <li class="">
    	<%=link_to ((t'activerecord.models.todo.more').capitalize), tabs_todos_path(string_for_klass(@klass), @klass.id ), class: "tab_tasks"%>
    </li>
    <li class="">
    	<%=link_to (t('activerecord.models.log.more' ).capitalize), tabs_logs_path(string_for_klass(@klass), @klass.id), class: "tab_logs"%>
    </li>
    <li class="">
    	<%=link_to (t('activerecord.models.milestone.more' ).capitalize), tabs_milestones_path(string_for_klass(@klass), @klass.id), class: "tab_milestones"%>
    </li>
    <% if can? :manage, User%>
    <li class="">
    	<%=link_to (t('activerecord.models.user.more' ).capitalize), tabs_users_path(string_for_klass(@klass), @klass.id), class: "tab_users"%>
    </li>
    <% end %>
    <li class="">
    	<%=link_to (t('navigation.statistics' ).capitalize), tabs_statistics_path(string_for_klass(@klass), @klass.id), class: "tab_statistics"%>
    </li>
    <%# <li class="">
        <#=link_to (t('navigation.spendings').capitalize), tabs_spendings_path(string_for_klass(@klass), @klass.id), class: "tab_spendings"#>
    </li> 
     #%>
    <%#<% if can? :read, Invoice %>
	    <%#<li class="">
	    	<%=link_to (t('activerecord.models.invoice.more' ).capitalize), tabs_invoices_path(string_for_klass(@klass), @klass.id), class: "tab_invoices"%>
	    <%#</li>
    <% end %>
  </ul>
</nav>

app/views/projects/_project.html.erb
<div id="project_list_<%= project.id %>">
<div class="info" id="project_info_<%= project.id %>">
  <div class="name_todo"><%= link_to project.name, project_path( project) %></div>
  <div class="project_desc"><%= truncate_string(project.description, 70, '...') %></div>
<div class="delete_edit">
<% if can? :manage, project %>
  <span class="open_project_update edit" id="project_update" data-id="<%= project.id %>" data-object="project"><%= t'edit' %></span>
<% end %>
<% if can? :archive, project %>
  <a class="activate_projects_no_button" data-object="project" data-id="<%= project.id.to_s %>"><%= t'general.archive_verb' %></a>
<% end %>
</div>
</div>
<% if can? :manage, project %>
<div class="dialog_form" id="project_update_<%= project.id %>_form" title="<%= t('helpers.submit.update', model: Project.model_name.human) %>" style="display:none;">
      <%= form_for(project, :remote => true) do |f| %>
      <ul>
      <li><%= f.label :name %><%= f.text_field :name %></li>
      <li><%= f.label :description %><%= f.text_area :description %></li>
      <li><%= f.submit (t'save'), :class => 'submit' %></li>
      </ul>
      <% end %>
</div>
<% end %>
</div>

app/views/projects/_projects_index.html.erb
<% if can? :manage, project %>
<li class="tab_list" id="project_<%= project.id.to_s %>"> 
	<div class="tab_list_text">
	<%= link_to truncate(project.name, :length => 80), project_path(project) %>
	</div>
	<div class="button_wrapper">
		<span class='view-tabs-list' data-id="<%= project.id %>" data-object="project" title="View project" data-firm-id="<%= current_firm.id %>"></span>
		<% if can? :manage, project %>
			<span class='open_project_update button edit' id="project_update" data-id="<%= project.id %>" data-object="project" title="Edit project"><%= t'edit' %></span>  
		<% end %>
		<% if can? :archive, project %>
			<a class="activate_project button" id="archive_<%= project.id.to_s %>" data-object="project" data-id="<%= project.id.to_s %>"><%= t'general.archive_verb' %></a>
		<% end %>
	</div>
	<div class="dialog_form" id="project_update_<%= project.id %>_form" title="<%= t('helpers.submit.update', model: Project.model_name.human) %>" style="display:none;"></div>
</li>
<% end %>

app/views/projects/activate_projects.js.erb
$(".flash_notice").empty()
$(".flash_notice").append("<%= escape_javascript(flash.discard(:notice))%>");
$("#project_<%= escape_javascript(@project.id.to_s)%>").remove();
$("#project_list_<%= escape_javascript(@project.id.to_s)%>").remove();
$('.spinning').hide();

app/views/projects/create.js.erb
$('.flash_error').empty();
$(".flash_notice").empty()
$(".flash_notice").append("<%= j(flash.discard(:notice))%>")
if(window.location.pathname.indexOf("customers") >= 0){
$("#listing_projects").append("<%= j(render(:partial => "project", :locals => {:project => @klass})) %>");	
}else{
$("#cus_pro_us_listing").prepend("<%= j( render :partial => "projects_index", :locals => { :project => @klass })  %>");
$(".button").button();	
}
$(".open_project_update").UIdialogs_edit_links();
$(".activate_project").activate_projects();
$(".activate_projects_no_button").activate_projects_no_button();
$('#dialog_project_form').empty().append("<%= j(render "form" )%>")
$("#new_project")[0].reset();
NProgress.done();

app/views/projects/destroy.js.erb
$(".flash_notice").empty()
$(".flash_notice").append("<%= escape_javascript(flash.discard(:notice))%>")
$("#project_<%= @klass.id %>").remove();
NProgress.done();

app/views/projects/edit.js.erb
$(".flash_notice").empty()
$(".flash_notice").append("<%= j(flash.discard(:notice))%>")
var form_wrapper = $("#project_update_<%= j (@project.id.to_s) %>_form")
form_wrapper.empty().append("<%= j( render "form")  %>")
// form_wrapper.find(".edit_project").validateWithErrors();
$("#date_project_<%= j (@project.id.to_s) %>").datepicker(); 
form_wrapper.find("select").chosen({width: '369px'});

app/views/projects/index.html.erb
<%= render ("projects/index")%>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/update.js.erb
$('.flash_error').empty();
$(".flash_notice").empty();
$(".flash_notice").append("<%= j(flash.discard(:notice))%>");
$("#project_<%= j(@klass.id.to_s)%>").replaceWith("<%= j( render :partial => "projects_index", :locals => { :project => @klass })  %>")
$(".button").button();
$("#project_list_<%= j(@klass.id.to_s)%>").replaceWith("<%= j(render @klass) %>")
$("#project_list_<%= j(@klass.id.to_s)%>").css("background-color", "#DBFFDE");
$(".activate_project").activate_projects();
$(".activate_projects_no_button").activate_projects_no_button();
$(".open_project_update").UIdialogs_edit_links();
$(".dialog_form:last").remove();
$("#description").replaceWith("<%= j( render :partial => 'projects/description') %>")
$('.budget').replaceWith("<%= j( render :partial => 'projects/budget') %>")
$(".budget_green").set_buget_width()
NProgress.done();

app/views/projects/update_index.js.erb
$('.flash_error').empty();
$(".flash_notice").empty();

$(".flash_notice").append("<%= escape_javascript(flash.discard(:notice))%>");
<% if request.path.match "projects" %>
$("#project_<%= escape_javascript(@project.id.to_s)%>").replaceWith("<%= escape_javascript(render @project) %>")
$("#project_<%= escape_javascript(@project.id.to_s)%>").css("background-color", "#DBFFDE");
<%else%>
$("#project_<%= escape_javascript(@project.id.to_s)%>").replaceWith("<%= escape_javascript( render :partial => "projects_index", :locals => { :project => @project })  %>")
<%end%>
$(".activate_project").activate_projects();
$(".open_project_update").UIdialogs_edit_links();
$("#dialog_project").UIdialogs_links();
$("#dialog_project_form").UIdialogs();
$(".dialog_form:last").remove();
NProgress.done();