config/routes.rb
  get "/index" => "public#index",  :as => :index

  resources :guides
  post "hooks/receiver"
    resources :firms
    post "public/create_firm" => "public#create_firm", :as => :create_firm
    resources :public do
      member do
        get "first_user"
        post "create_first_user"
     end
  end  
  ActiveAdmin.routes(self)
  get '/obeqaslksdssdfnfdfysdfxm/dashboard/subscription_chart_data' =>  'obeqaslksdssdfnfdfysdfxm/dashboard#subscription_chart_data'
  get '/obeqaslksdssdfnfdfysdfxm/dashboard/firms_chart_data' =>  'obeqaslksdssdfnfdfysdfxm/dashboard#firms_chart_data'
  get '/obeqaslksdssdfnfdfysdfxm/dashboard/firms_resources_chart_data' =>  'obeqaslksdssdfnfdfysdfxm/dashboard#firms_resources_chart_data'
  get '/obeqaslksdssdfnfdfysdfxm/dashboard/new_firms_count_chart_data' =>  'obeqaslksdssdfnfdfysdfxm/dashboard#new_firms_count_chart_data'
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for  :users,
              :path_names => { :sign_up => "register" },
              :controllers => {
              :sessions => "sessions",
              :passwords => "passwords",
              :registrations => "users"
             }

  devise_scope :user do
  	get "/sign_in", :to => "sessions#new"
    delete "/sign_out", :to => "sessions#destroy"
    get "register", :to => "public#register"
  	get "contact", :to => "public#contact"
    get "/sign_in_at_subdomain" =>  "sessions#sign_in_at_subdomain", :as => :sign_in_at_subdomain
  	get "/register/:firm_id/user" => "public#first_user",  :as => :register_user
  	post "/register/:firm_id/user" => "public#create_first_user",  :as => :create_first_user
  	get "/validates_uniqe/:subdomain" => "public#validates_uniqe", :as => :validates_uniqe
    get '/users/password/edit' =>  'devise/passwords#edit', :as => :edit_password
  end
  
  


  constraints(Subdomain) do
    post 'emails/create/:id' => 'emails#create', as: :emails
    get 'emails/:id/new' => 'emails#new', as: :new_email
    get 'emails/:id/reminder' => 'emails#reminder', as: :reminder_email
    post 'emails/reminder_create/:id' => 'emails#reminder_create', as: :reminder_create
    get "/emails/quick_send/:id" => "emails#quick_send", :as => :quick_send
    get "plans" => 'plans#index', :as => :plans
    # delete "plans/index", :as => :plans_delete
    get "plans/cancel", :as => :plans_cancel
    resources :subscriptions
    get "payments" => 'payments#index', :as => :payments
    get "payments/:id" => 'payments#show', :as => :payment
    get "payments/download_pdf/:id" => 'payments#download_pdf', :as => :download_pdf
    constraints(PaymentChecker) do
      # devise_for  :users
      resources :users, :only => [:index, :show, :edit, :create, :update, :destroy] do
        member do
         get :valid
        end
      end
      #chart_controller
      get "charts" => "charts#index", :as => :charts
      get "users_logs" => "charts#users_logs",  :as => :users_logs
      get "project_users_logs" => "charts#project_users_logs",  :as => :project_users_logs
      get "project_todos_logs" => "charts#project_todos_logs",  :as => :project_todos_logs
      # get "customer_users_logs" => "charts#customer_users_logs",  :as => :customer_users_logs
      # get "customer_todos_logs" => "charts#customer_todos_logs",  :as => :customer_todos_logs
      get "projects_logs" => "charts#projects_logs",  :as => :projects_logs
      get "customers_logs" => "charts#customers_logs",  :as => :customers_logs
      get "dashboard_json" => "charts#dashboard_json",  :as => :dashboard_json
      get "statistics" => "charts#statistics",  :as => :statistics
      get "economicstatistics_json" => "charts#economicstatistics_json",  :as => :economicstatistics_json
      #projects_controller
      get "/archive" => "projects#archive",  :as => :archive
      put "projects/update_index/:id" => "projects#update_index",  :as => :update_index
      post "projects/create_index/" => "projects#create_index",  :as => :create_index
      post "/activate_projects/:id" => "projects#activate_projects", :as => :activate_projects
      #tabs_controller
      get "/:class/:id/state"       => "tabs#state", :as => :tabs_state
      get "/:class/:id/tasks"       => "tabs#todos", :as => :tabs_todos
      get "/:class/:id/milestones"  => "tabs#milestones", :as => :tabs_milestones
      get "/:class/:id/projects"    => "tabs#projects", :as => :tabs_projects
      get "/:class/:id/employees/"  => "tabs#employees", :as => :tabs_employees
      get "/:class/:id/logs"        => "tabs#logs", :as => :tabs_logs
      get "/:class/:id/users"       => "tabs#users", :as => :tabs_users
      get "/:class/:id/statistics"  => "tabs#statistics", :as => :tabs_statistics
      get "/:class/:id/spendings"   => "tabs#spendings", :as => :tabs_spendings
      get "/:class/:id/invoices"    => "tabs#invoices", :as => :tabs_invoices
      #logs_controller
      post "logs/start_tracking" => "logs#start_tracking",  :as => :start_tracking
      patch "logs/stop_tracking/:id" => "logs#stop_tracking",  :as => :stop_tracking
      get "/get_logs_todo/:todo_id" => "logs#get_logs_todo", :as => :get_logs_todo
      #select_controller
      get "/project_select/:project_id/:log_id" => "select#project_select"
      get "/project_select/:project_id/" => "select#project_select"

      get "/customer_select/:customer_id/:log_id" => "select#customer_select"
      get "/customer_select/:customer_id/" => "select#customer_select"
      get "/todo_select/:todo_id/:log_id" => "select#todo_select"
      get "/todo_select/:todo_id/" => "select#todo_select"
      post "/customer_select_tracking/:customer_id/:log_id" => "select#customer_select_tracking"
      post "/customer_select_tracking/:customer_id/" => "select#customer_select_tracking"

      post "/employee_select_tracking/:employee_id/:log_id" => "select#employee_select_tracking"
      post "/employee_select_tracking/:employee_id/" => "select#employee_select_tracking" 

      post "/project_select_tracking/:project_id/:log_id" => "select#project_select_tracking"
      post "/project_select_tracking/:project_id/" => "select#project_select_tracking"
      
      post "/todo_select_tracking/:todo_id/:log_id" => "select#todo_select_tracking"
      post "/todo_select_tracking/:todo_id/" => "select#todo_select_tracking"

      #timesheets_controller
      get "/timesheetWeek"   => "timesheets#timesheet_week"
      get "/timesheetMonth"  => "timesheets#timesheet_month"

      get "/:class/:id/timesheet_day/:date"   => 'timesheets#timesheet_day',   :as => :timesheet_day
      get "/:class/:id/timesheet_week/:date"   => 'timesheets#timesheet_week',   :as => :timesheet_week
      get "/:class/:id/timesheet_month/:date"  => "timesheets#timesheet_month",  :as => :timesheet_month
      
      post "/add_hour_to_project/" => 'timesheets#add_hour_to_project', :as => :add_hour_to_projects
      post "/add_log_timesheet" => 'timesheets#add_log_timesheet', :as => :add_log_timesheet
      #reports_controller
      get "/reports" => 'reports#index', :as => :reports
      get "/squadlink_report" => 'reports#squadlink_report', :as => :squadlink_report
      get "/dashboard" => 'reports#dashboard', as: :dashboard
      #memberships_controller
      post "/membership/:id/:project_id" => "memberships#index", :as => :membership
      #firms_controller
      put "/firm_update" => "firms#firm_update",  :as => :firm_update
      get "/account" => "firms#firm_show",  :as => :firm_show
      #roster
      get "/roster_milestone" => "roster#get_milestones", :as => :roster_milestone
      get "/roster_task" => "roster#get_tasks", :as => :roster_task
      #timerange
      # get "/logs_pr_date/:time/:url" => "timerange#logs_pr_date", :as => :logs_pr_date
      # match "/logs_pr_date" => "timerange#logs_pr_date", :as => :logs_pr_date
      get "/log_range/" => "timerange#log_range", :as => :log_range
      get "/todo_range/" => "timerange#todo_range", :as => :todo_range
      get "/invoice_range/" => "timerange#invoice_range", :as => :invoice_range
      # get "/todos_pr_date/:time/:url/:id" => "timerange#todos_pr_date", :as => :todos_pr_date 
      #invoices
      get "/invoices/customer_select/" => "invoices#customer_select"
      get "/invoices/project_select/" => "invoices#project_select"
      post "/invoices/customers_create/" => "invoices#customers_create"
      post "/invoices/projects_create/" => "invoices#projects_create"
      get "/invoices/:id/slow_sending/" => "invoices#slow_sending"
      get "/invoices/:id/credit_note/" => "invoices#credit_note"
      post "/invoices/:id/credit_note_create/" => "invoices#credit_note_create", :as => :credit_note_create

      # post "/jobs/sending_invoice/" => "jobs#sending_invoice", :as => :sending_invoice
      post "/jobs/handeling_invoice/" => "jobs#handeling_invoice", :as => :handeling_invoice
      
      get "/jobs/download/:id" => "jobs#download", :as => :download
      post "/jobs/invoice_paid/:id" => "jobs#invoice_paid", :as => :invoice_paid
      post "/jobs/invoice_lost/:id" => "jobs#invoice_lost", :as => :invoice_lost
      patch "/jobs/create_slow_sending/:id" => "jobs#create_slow_sending", :as => :create_slow_sending
      get "/jobs/fetch_job/" => "jobs#fetch_job", :as => :fetch_job
      get "/jobs/ajax_download/" => "jobs#ajax_download", :as => :ajax_download
      get "/jobs/ajax_sending/" => "jobs#ajax_sending", :as => :ajax_sending
      get "/jobs/time_out/" => "jobs#time_out", :as => :time_out
      get "jobs/download_invoice/:id" => "jobs#download_invoice", :as => :download_invoice
      get "jobs/show_pdf/:id" => "jobs#show_pdf", :as => :show_pdf
      get "/invoice_pdf/:id" => "pdf#invoice", :as => :invoice_pdf
      resources :invoices 
      resources :customers
      resources :employees
      resources :projects
      resources :milestones
      resources :todos
      resources :logs
      get "/", :to  => "logs#index"
    end
    get "/", :to  => "plans#index"
	end
  root :to => "public#index"

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	def index
     authorize! :read, Firm
     if can? :manage, Firm
  	 @users = current_firm.users
  	 @projects = current_firm.projects
  	 @customers = current_firm.customers
    else
     @users = User.where(id: current_user.id)
     @projects = current_user.projects
     @customers = current_firm.customers
   end
  end
  
  def squadlink_report
    authorize! :read, Firm
    range = (params[:from].to_date..params[:to].to_date)
  	@logs = current_firm.logs
                        .where.not(end_time: nil)
  	                    .where(log_date: range)
  	                    .order(:log_date)
  	                    .includes(:user, :project, :customer)
  	                    .try_find_logs(user_id: params[:user_id],
                                       project_id: params[:project_id], 
                                       customer_id: params[:customer_id])
                
    respond_to do |format|
      format.html
      format.csv do
        response.headers['Content-Disposition'] = 'attachment; filename="squadlink_report.csv"'
        render "squadlink_report", formats: [:csv], handler: [:erb]
      end
      format.xls do
        response.headers['Content-Disposition'] = 'attachment; filename="squadlink_report.xls"'
        render "squadlink_report", formats: [:xls], handler: [:erb]
      end
    end
  end
  def dashboard
    authorize! :read, Firm
    @users = current_firm.users.includes(:logs).order(:current_sign_in_at)
    @log_worth = LogWorker.calulate_logs_worth(current_firm.logs.uninvoiced.group(:rate).sum(:hours)).try(:prettify_to_s)
    @tasks_overdue_and_to_day = current_user.todos.overdue_and_to_day
    # @logs = @klass.logs.order("log_date DESC").limit(3).includes(:user)
    @logs_uninvoiced = current_firm.logs.uninvoiced.sum(:hours)
  end
end   

app/views/reports/dashboard.html.erb
<%= render "shared/home_header" %>
<div id="left" class="home_content">
<div class="dashboard">


<div class="state_wrapper">
	<% if !@tasks_overdue_and_to_day.blank? %>
	<div class="db_state_logs">
	  	<div class="state_headers"><%= (t'activerecord.models.todo.more').capitalize %></div>
	  	<ul class="dashboard_tasks">	
  <% @tasks_overdue_and_to_day.each do |todo|%>
  <li id="db_todo_<%=todo.id%>">
  	<div class="dashboard_row_task <% if todo.overdue %>red<% else %>green<% end %>" >
  		<%= form_for todo, :remote => true, :html => {:id => "db_edit_done_todo_#{todo.id}"} do |f| %>
      <div class="priority_todo <%=todo_priority(todo.prior)%>" title="Priority"></div>
  		<%= f.check_box :completed, :class => "db_done_box", :id => todo.id %>
	  	<% end %>
	  	<% if todo.project %>
	  	<%= link_to todo.name, tabs_todos_path("projects", todo.project.id ) %>
	  	<% else %>
	  	<%= link_to todo.name, tabs_todos_path("customers", todo.customer.id)%>
	  	<% end %>
  	</div> 
  </li>
 
  <%end%>
</ul>
	</div>
 <% end %>
	
<div class="state_headers"><%= t'general.latest_activity' %></div>
	<ul>
	  <% @users.each do |user|%>
	  <% if user.current_sign_in_at != nil%>
	  <li>
	  	<span class="db_user_name"><%= link_to user.name, user_path(user) %></span> <span style="color:green"><%= t"general.online" %></span></li>
	  	 <%else%>
	  	 <li><span class="db_user_name" style="color:gray; font-style:italic"><%= user.name %></span> <span style="color:#FC6868"><%= t"general.offline" %></span></li>
	  	 <%end%>
	  	<ul>
	  	<% user.logs.order("log_date DESC").limit(3).each do |log| %>   
	    <li class="db_user_logs">
	    	<div class="db_log_header">
	    	<span class="date_format_setter" style="font-weight:bold;" data-date="<%= log.log_date %>"><%= log.log_date %></span>|
	  		<% if log.end_time.nil? %>
	  			<span style=""><%=link_to( t('general.in_progress'), logs_path) %></span>
				<% else %>
				<div class="total_log_time in_db" data-hours="<%= log.hours %>">0:00</div><%= t'times.hour.more' %>
					
				<% end %>
				</div>
				<%= truncate(log.event , length: 40) %> 
			</li>
		<% end %>
		</ul>		  
	  <%end%>
	</ul>
</div>
<div id="description">
	<div id="dashboard_charts" style="float:left;width:600px;">	
		<div class="state_headers dashboard_chart_display"><%=  t'dashboard.time_spent_projects' %></div><div class="state_headers dashboard_chart_display"><%=  t'dashboard.time_spent_users' %></div>  
	<div class="one_month_back" data-lastmonth="<%= date_format(time_zone_now.to_date - 1.month) %>" data-today="<%= date_format(time_zone_now.to_date) %>"></div>
	<div id="project_pie" class="dashboard_chart_display">	
		<svg style="height:300px; width:300px;"></svg>
		</div>
	
	<div id="user_pie" class="dashboard_chart_display">	
		<svg style="height:300px; width:300px;"></svg>
		</div>
		<div class="state_headers dashboard_income_chart_display"><%=  t'dashboard.income_last_12' %></div>
		<div id="income_stack" style="float:left;height:100px; width:600px;">	

		<svg style="height:100px; width:600px;"></svg>
		</div>
	</div>
	<% if !@logs_uninvoiced.blank? %>

	  	<div class="state_headers"><%= t('economic.uninvoiced') %></div>
	  	<div class="state_log"><%= time_format(@logs_uninvoiced.to_f) %> <%= t('times.hour.more' )%>, 
	  		<%= t('economic.value' )%> <%= currency_converter(@log_worth)%></div>


 <% end %>
	</div>

 
	</div>
</div>
</div>
</div>

app/views/reports/index.html.erb
<div id="left" class="home_content">
<%= render "shared/home_header" %>
  	<div class="html_tab_content" id="tabs-1"> 
  		<div class="timesheet">
  	<%= form_tag "/squadlink_report", :method => :get %>
  	<ul class="report_form">
		<li><%= t'general.range' %> <span class="right"><%= text_field_tag 'from',date_format(time_zone_now.to_date - 1.month),  :class => "range_date"%>  
			<%= text_field_tag 'to',date_format(time_zone_now.to_date), :class => "range_date", :style => "font-size:80%;"  %></span></li>
			
			
		<li><%= t('activerecord.models.user.one').capitalize %>    
			<span class="right">
			<select class="range_select" id="user_id" name="user_id">
				<option value=""><%= t('general.select') %> <%= t('activerecord.models.user.one').capitalize %></option>
				<% @users.each do |user| %>
					<option value="<%= user.id %>"><%= user.name %></option>
					<% end %>
				</select>
			</span>
		</li> 
		<li><%= t('activerecord.models.project.one').capitalize %>     
			<span class="right">
			<select class="range_select" id="project_id" name="project_id">
				<option value=""><%= t('general.select') %> <%= t('activerecord.models.project.one').capitalize %></option>
				<% @projects.each do |project| %>
					<option value="<%= project.id %>"><%= project.name %></option>
					<% end %>
				</select>
			</span>
		</li>  		
		<li><%= t('activerecord.models.customer.one').capitalize %>     
			<span class="right">
			<select class="range_select" id="customer_id" name="customer_id">
				<option value=""><%= t('general.select') %> <%= t('activerecord.models.customer.one').capitalize %></option>
				<% @customers.each do |customer| %>
					<option value="<%= customer.id %>"><%= customer.name %></option>
					<% end %>
				</select>
			</span>
		</li> 
		<li>Format     
			<span class="right">
			<select class="format_select" id='format' name='format'>
	  			<option value='html' selected='selected'><%= (t'general.view_in_brower') %> (HTML)</option>
	  			<option value='csv'><%= (t'general.export_to_csv') %> (CSV)</option>
	  			<option value='xls'><%= (t'general.export_to_excel') %> (XLS)</option>
			</select>
			</span> 	
		</li>	 		
  		<li><%= submit_tag (t'general.generate_report') , :class => 'submit' %></li>

  	</ul>
	</div>
	</div>
 </div>

app/views/reports/squadlink_report.csv.erb
<%= t'activerecord.attributes.log.log' %>,<%= t'activerecord.attributes.log.hour' %>,<%= t'activerecord.attributes.log.user' %>,<%= t'activerecord.attributes.log.project' %>,<%= t'activerecord.attributes.log.customer' %>,<%= t'activerecord.attributes.log.date' %>,
    <% @logs.each do |log| %>
      <%= log.event %>,<%= time_format(log.hours ) %>,<%= log.user.try(:name) %>,<%= log.customer.try(:name) %>,<%= log.project.try(:name) %>,<%= date_format(log.log_date) %>,
    <% end %>

app/views/reports/squadlink_report.html.erb
<div id="left" class="home_content">
<%= render "shared/home_header" %>
  	<div class="html_tab_content" id="tabs-1"> 
	
<table class="report_table">
<tr>
<th class="report_event"><%= t'activerecord.attributes.log.log' %></th>
<th class="report_hours"><%= t'activerecord.attributes.log.hour' %></th>
<th class="report_user"><%= t'activerecord.attributes.log.user' %></th>
<th class="report_customer"><%= t'activerecord.attributes.log.customer' %></th>
<th class="report_project"><%= t'activerecord.attributes.log.project' %></th>
<th class="report_date"><%= t'activerecord.attributes.log.date' %></th>
</tr>
<% if @logs %>
<% @logs.each do |log| %>
<tr>
<td class="report_event"><%= simple_format(log.event, class: 'log_event_paragraf') %></td>
<td class="report_hours"><%= time_format(log.hours )%></td>
<td class="report_user"><%= log.user.try(:name) %></td>
<td class="report_project"><%= log.customer.try(:name) %></td>
<td class="report_customer"><%= log.project.try(:name) %></td>
<td class="report_date"><%= date_format(log.log_date) %></td>
</tr>
<% end %>
<% end %>
</table>
  		
	</div>
 </div>

app/views/reports/squadlink_report.xls.erb
<table class="report_table">
<tr>
<th class="report_event"><%= t'activerecord.attributes.log.log' %></th>
<th class="report_hours"><%= t'activerecord.attributes.log.hours' %></th>
<th class="report_user"><%= t'activerecord.attributes.log.user' %></th>
<th class="report_project"><%= t'activerecord.attributes.log.project' %></th>
<th class="report_project"><%= t'activerecord.attributes.log.todo' %></th>
<th class="report_customer"><%= t'activerecord.attributes.log.customer' %></th>
<th class="report_customer"><%= t'activerecord.attributes.log.employee' %></th>
<th class="report_date"><%= t'activerecord.attributes.log.date' %></th>
</tr>
<% if @logs %>
<% @logs.each do |log| %>
<tr>
<td class="report_event"><%= log.event %></td>
<td class="report_hours"><%= time_format(log.hours ) %></td>
<td class="report_user"><%= log.user.try(:name) %></td>
<td class="report_customer"><%= log.project.try(:name) %></td>
<td class="report_customer"><%= log.todo.try(:name) %></td>
<td class="report_project"><%= log.customer.try(:name) %></td>
<td class="report_project"><%= log.employee.try(:name) %></td>
<td class="report_date"><%= date_format(log.log_date) %></td>
</tr>
<% end %>
<% end %>
</table>

<%= t'activerecord.attributes.log.log' %>